name: Build Custom Kali Linux ISO

on:
  push:
    branches:
      - main

jobs:
  build-kali-iso:
    runs-on: kali-rolling

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up environment
        run: |
          sudo apt update
          sudo apt install -y debootstrap live-build git curl

      - name: Install Kali Linux dependencies
        run: |
          sudo apt install -y kali-archive-keyring kali-debian-archive-keyring kali-archive-keyring \
            kali-linux-default kali-linux-large kali-linux-sdr kali-linux-wireless

      - name: Clone Kali Linux live-build-config repository
        run: git clone https://gitlab.com/kalilinux/build-scripts/live-build-config.git

      - name: Build Custom ISO
        run: |
          cd live-build-config
          sudo ./build.sh --variant light --arch amd64 --verbose

      - name: Customize ISO
        env:
          ENVIRONMENT: gnome  # Options: gnome, lxde, xfce, kde, cli
          TYPE: live          # Options: live, installer
          PRESET: medium      # Options: light, medium, high
        run: |
          cd live-build-config
          case ${{ env.ENVIRONMENT }} in
            gnome)
              sudo ./build.sh --variant light --arch amd64 --verbose --variant gnome
              ;;
            lxde)
              sudo ./build.sh --variant light --arch amd64 --verbose --variant lxde
              ;;
            xfce)
              sudo ./build.sh --variant light --arch amd64 --verbose --variant xfce
              ;;
            kde)
              sudo ./build.sh --variant light --arch amd64 --verbose --variant kde
              ;;
            cli)
              sudo ./build.sh --variant light --arch amd64 --verbose --variant cli
              ;;
            *)
              echo "Unknown environment: ${{ env.ENVIRONMENT }}"
              exit 1
              ;;
          esac
          case ${{ env.TYPE }} in
            live)
              sudo ./build.sh --variant light --arch amd64 --verbose --live
              ;;
            installer)
              sudo ./build.sh --variant light --arch amd64 --verbose --installer
              ;;
            *)
              echo "Unknown type: ${{ env.TYPE }}"
              exit 1
              ;;
          esac
          case ${{ env.PRESET }} in
            light)
              sudo ./build.sh --variant light --arch amd64 --verbose --preset light
              ;;
            medium)
              sudo ./build.sh --variant light --arch amd64 --verbose --preset medium
              ;;
            high)
              sudo ./build.sh --variant light --arch amd64 --verbose --preset high
              ;;
            *)
              echo "Unknown preset: ${{ env.PRESET }}"
              exit 1
              ;;
          esac

      - name: Upload ISO artifact
        uses: actions/upload-artifact@v2
        with:
          name: custom-kali-linux-iso
          path: live-build-config/images/*.iso
