name: Download and Execute

on:
  workflow_dispatch:
    inputs:
      download_link:
        description: 'Enter the download link for the file'
        required: true
      command:
        description: 'Enter the command to execute after downloading'
        required: true

jobs:
  download-and-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Download file using curl
        run: |
          echo "Downloading from: ${{ github.event.inputs.download_link }}"
          curl -o block.py ${{ github.event.inputs.download_link }}

      - name: Run the command
        run: |
          echo "Running command: ${{ github.event.inputs.command }}"
          ${{ github.event.inputs.command }}
