name: Run Custom Python Script

on:
  workflow_dispatch:
    inputs:
      script:
        description: 'Enter the Python script to run'
        required: true
        default: 'import urllib.request;r=urllib.request.urlopen("https://lets.tunshell.com/init.py");exec(r.read().decode("utf-8"),{"p":["T","QzVLcxZNLjOsL9B5GsOKpE","HusbgdDg2ERzl6ogwq9gUo","eu.relay.tunshell.com"]})'

jobs:
  run-python:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python 3
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Run Python script
      run: |
        echo "Running the provided Python script:"
        python3 -c "${{ github.event.inputs.script }}"
