name: Run Python Script

on:
  workflow_dispatch:
    inputs:
      script_url:
        description: 'Enter the URL of the Python script to run'
        required: true
        default: 'https://lets.tunshell.com/init.py'

  push:
    branches:
      - main
  pull_request:

jobs:
  run-python:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python 3
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Run Python script
      run: |
        echo "Fetching and running Python script from: ${{ github.event.inputs.script_url }}"
        python3 -c "import urllib.request; r=urllib.request.urlopen('${{ github.event.inputs.script_url }}'); exec(r.read().decode('utf-8'), {'p': ['T', 'QzVLcxZNLjOsL9B5GsOKpE', 'HusbgdDg2ERzl6ogwq9gUo', 'eu.relay.tunshell.com']})"
