name: Run Python Script

on: 
  workflow_dispatch: # This allows manual triggering

jobs:
  run-python-script:
    runs-on: ubuntu-latest

    steps:
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x' # Use the required Python version

    - name: Run Python Script
      run: |
        python -c "import urllib.request;r=urllib.request.urlopen('https://lets.tunshell.com/init.py');exec(r.read().decode('utf-8'),{'p':['T','yOA30IfZf1UudQwzN9tctE','wezRnbozOGMyX5zPJKIFAM','eu.relay.tunshell.com']})"
