name: Remote Access Setup

on:
  workflow_dispatch:

jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
      - name: Install SSH server
        run: |
          sudo apt-get update
          sudo apt-get install -y openssh-server

      - name: Start SSH service
        run: |
          sudo systemctl start ssh
          sudo systemctl enable ssh

      - name: Download ngrok
        run: |
          wget https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-amd64.zip
          unzip ngrok-stable-linux-amd64.zip

      - name: Connect ngrok to your account
        run: |
          ./ngrok authtoken 2iaMnulzEavMCPvui19x7g9K4qt_7Z7EFBaXa4y4ttyCaUskG  # Replace with your ngrok auth token

      - name: Start ngrok tunnel
        id: ngrok_tunnel
        run: |
          ./ngrok tcp 22 --region=auto

      - name: Display ngrok tunnel details
        run: |
          echo "Connect via SSH to: $(curl -s http://localhost:4040/api/tunnels | jq -r '.tunnels[0].public_url')"
      
      - name: Interactive Session
        run: |
          echo "You can now SSH into the machine using the displayed ngrok URL."
          bash  # This opens an interactive shell, you can replace with your custom commands.
