name: XRDP Remote Desktop Setup

on:
  workflow_dispatch:

jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
      - name: Update Snap and Install ngrok
        run: |
          sudo snap refresh
          sudo snap install ngrok

      - name: Install XRDP and XFCE Desktop Environment
        run: |
          sudo apt update
          sudo apt install -y xrdp xfce4 xfce4-goodies
          sudo systemctl enable xrdp
          sudo systemctl start xrdp
          echo xfce4-session > ~/.xsession

      - name: Allow RDP Port through Firewall
        run: |
          sudo ufw allow 3389/tcp
          sudo ufw enable

      - name: Create ngrok Config Directory
        run: |
          mkdir -p ~/.ngrok2
          echo "web_addr: localhost:4040" > ~/.ngrok2/ngrok.yml

      - name: Authenticate ngrok
        run: |
          ngrok authtoken 2iaMnulzEavMCPvui19x7g9K4qt_7Z7EFBaXa4y4ttyCaUskG

      - name: Start ngrok Tunnel for RDP
        run: |
          ngrok tcp 3389 --region=in

      - name: Display ngrok Tunnel Information
        run: |
          echo "Connect using Remote Desktop Protocol (RDP) to:"
          ngrok http 3389
