name: XRDP via Local Tunnel

on:
  workflow_dispatch:

jobs:
  expose_rdp_tunnel:
    runs-on: ubuntu-latest
    steps:
      - name: Install xrdp and dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y xrdp
          sudo systemctl start xrdp
          sudo systemctl enable xrdp
      
      - name: Install localtunnel
        run: npm install -g localtunnel
      
      - name: Start localtunnel for RDP
        id: localtunnel
        run: |
          lt --port 3389 > tunnel_info.txt &
          sleep 10 # Allow time for localtunnel to start and provide URL
          cat tunnel_info.txt | grep -oP '(?<=url: ).*' > url.txt

      - name: Display tunnel URL
        run: |
          echo "Connect using Remote Desktop Protocol (RDP) to $(cat url.txt)"

      - name: Keep workflow running
        run: sleep infinity
