name: Dynamic Upload Artifact

on: [workflow_dispatch]

jobs:
  dynamic-upload:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install GitHub CLI
      run: sudo apt-get install gh -y

    - name: Keep workflow running and allow dynamic uploads
      run: |
        chmod +x ./upload.sh
        ./upload.sh
