name: Serveo SSH Tunnel

on:
  workflow_dispatch:

jobs:
  serveo_ssh:
    runs-on: ubuntu-latest
    steps:
      - name: Install SSH Client
        run: sudo apt update && sudo apt install -y openssh-client

      - name: Install jq (JSON Processor)
        run: sudo apt install -y jq

      - name: Start Serveo Tunnel
        id: serveo
        run: |
          ssh -o StrictHostKeyChecking=no -R 80:localhost:22 serveo.net > serveo_url.txt &
          sleep 10  # Allow time for Serveo to start and provide the URL
          cat serveo_url.txt | grep -oP '(?<=url: ).*' > serveo_url_final.txt

      - name: Display Serveo URL
        run: |
          serveo_url=$(cat serveo_url_final.txt)
          echo "Connect using SSH to: $serveo_url"
          echo "::set-output name=url::$serveo_url"
        env:
          SERVEO_URL: ${{ steps.serveo.outputs.url }}
